services:
  - type: web
    name: skywatch-ua
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /healthz
    autoDeploy: true
